### ISSUE TITLE
Squashing commits

### ISSUE THREAD

**Issue by camjac251** [sixem/eyy-indexer#10]
Would it be possible to not squash your commits on the develop branch? I wanted to go back and see only the theme commit but am unable to with them all as one.

I can't understand the themes feature. I added the path to the folder in the config but there's no way to change the theme on the page.

**Comment by soarn** [comment]
I'm also wondering this, do you set it up like:
```php
 'themes' => '/indexer/css/themes/pelagic.css',
```
or
```php
 'themes' => 'pelagic.css',
```

**Comment by sixem** [comment]
> 
> 
> Would it be possible to not squash your commits on the develop branch? I wanted to go back and see only the theme commit but am unable to with them all as one.
> 
> I can't understand the themes feature. I added the path to the folder in the config but there's no way to change the theme on the page.

There should be a drop down menu that you can toggle in the top right corner where you can set settings like themes etc.

> 
> 
> I'm also wondering this, do you set it up like:
> 
> ```
>  'themes' => '/indexer/css/themes/pelagic.css',
> ```
> 
> or
> 
> ```
>  'themes' => 'pelagic.css',
> ```

`'themes' => '/indexer/css/themes/` is how you would set it in this case, then the script will take any `.css` files from that directory and treat them as separate themes.

**Comment by sixem** [comment]
I'll close this now as there have been no more questions. Feel free to submit a new issue if you have any other issues, or if you have any questions.
