### ISSUE TITLE
Changing date format

### ISSUE THREAD

**Issue by camjac251** [sixem/eyy-indexer#11]
Could it be possible to change the date formatting? I had modified it before but I think the javascript overrides the php file's date variables.

I was hoping to set something like this `D m/d/y h:i A` which would look something like this `Sat 07/11/20 09:54 PM`

**Comment by sixem** [comment]
Good idea, and you are right, the JS does override the formatting because of the timezone adjustments. I think this should be fixable though, i just need to find a way to utilize the same date format for both PHP and JS. I'll see what i can do.

**Comment by sixem** [comment]
I've added a commit to the [dev](https://github.com/sixem/eyy-indexer/tree/dev) branch. Hopefully it should work now. The `date` option can now be set to either `array('desktop_format', 'mobile_format')` or just a regular `string` if they should both be the same format, i wouldn't recommend this though as the mobile screen space is very limited with these tables.

**Comment by sixem** [comment]
A date format option has been added. (#13)

**Comment by sixem** [comment]
That's weird. Can you double check that you've updated all of the files? This used to be the issue before the latest release but it should be resolved now.

I tried using the same format as you and i can't reproduce it when reloading the page.

![VG5L](https://user-images.githubusercontent.com/2825338/90985963-9fa1a680-e57f-11ea-9ec3-6669292e2d7f.gif)
