### ISSUE TITLE
Detect Timezone of user

### ISSUE THREAD

**Issue by camjac251** [sixem/eyy-indexer#5]
This is a small thing but I can't figure it out myself. I am modifying `strftime` but notice that by default the timezone is set to UTC in my case.

Would it be possible to set the timezone of the script to the user's IP address through geoip? Or through javascript?
https://stackoverflow.com/questions/39567799/how-do-i-find-user-timezone-in-php
https://momentjs.com/timezone/

**Comment by sixem** [comment]
At the moment the script will use whatever timezone your server has set.

But yeah, i think it should be possible to update this on page load to the timezone of the user, using Javascript. I'll look into it soon.
